spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      data-source-properties:
        sslMode: require

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    root: WARN
    com.gymcrm: INFO
